type: ch5

play_data:
  multi_process_num: 24
  nb_game_in_file: 1
  max_file_num: 800
  drop_draw_game_rate: 0.98

play:
  simulation_num_per_move: 200
  share_mtcs_info_in_self_play: True
  reset_mtcs_info_per_game: 1
  thinking_loop: 10
  use_newest_next_generation_model: True

trainer:
  batch_size: 16
  delete_self_play_after_number_of_training: 1
  min_data_size_to_learn: 1500
  save_model_steps: 100
  logging_per_steps: 25
  wait_after_save_model_ratio: 0
  lr_schedules:
  - [0, 0.01]
  - [500000, 0.001]
  - [1000000, 0.0001]
  - [1500000, 0.00001]
